# from ropensci
language: r
latex: false
fortran: false
env:
  - _R_CHECK_FORCE_SUGGESTS_=false

addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:cran/imagemagick'
    packages:
      - libmagick++-dev
      - librsvg2-dev
      - libwebp-dev
      - libpoppler-cpp-dev
      - r-cran-rgdal
      - libfftw3-dev
      - cargo
      - gsfonts

after_success:
  - Rscript -e 'covr::codecov()'
